---
language: java
jdk:
- oraclejdk8

# http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false

before_install:
- rvm install 2.2.5
- rvm use 2.2.5
- bash set-environment.sh

# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true  # if we don't skip install, ./gradlew assemble is invoked, but this task is not available.

# format from https://docs.travis-ci.com/user/caching/#Enabling-multiple-caching-features
cache:
  bundler: true
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/